NAME = typing-am
APP = /home/james/ics2019/nexus-am/apps/typing/build/typing-x86-navy
OBJS = /home/james/ics2019/nexus-am/apps/typing/build/x86-navy//game.o /home/james/ics2019/nexus-am/apps/typing/build/x86-navy//draw.o /home/james/ics2019/nexus-am/apps/typing/build/x86-navy//font.o /home/james/ics2019/nexus-am/apps/typing/build/x86-navy//keyboard.o /home/james/ics2019/nexus-am/am/build/am-x86-navy.a /home/james/ics2019/nexus-am/libs/klib/build/klib-x86-navy.a
LIBS += libndl
include /home/james/ics2019/navy-apps/Makefile.app
